### ISSUE TITLE
Failed child job enqueue results in a parent job that never 'completes'

### ISSUE THREAD

**Issue by holoiii** [anujdas/sidekiq-hierarchy#3] opened 2016-03-28 18:08 UTC
Hi there,

I have a worker set up like this:

``` ruby
class ParentWorker
  include Sidekiq::Worker
  sidekiq_options workflow: true

  def perform
    some_string = fetch_string    
    ChildWorker.perform_async(some_string)
  end
end
```

Where `fetch_string` pulls from a user uploaded csv file. The problem is, `some_string` is sometimes invalid, and I get this error `Encoding::UndefinedConversionError: "\x8F" from ASCII-8BIT to UTF-8` way down in the `json` library.

The stack trace looks like this:

```
vendor/ruby-2.0.0/lib/ruby/2.0.0/json/common.rb:224 in encode
vendor/ruby-2.0.0/lib/ruby/2.0.0/json/common.rb:224 in generate
vendor/ruby-2.0.0/lib/ruby/2.0.0/json/common.rb:224 in generate
vendor/bundle/ruby/2.0.0/gems/sidekiq-4.1.0/lib/sidekiq.rb:145 in dump_json
vendor/bundle/ruby/2.0.0/gems/sidekiq-4.1.0/lib/sidekiq/client.rb:189 in block in atomic_push
vendor/bundle/ruby/2.0.0/gems/sidekiq-4.1.0/lib/sidekiq/client.rb:187 in map
vendor/bundle/ruby/2.0.0/gems/sidekiq-4.1.0/lib/sidekiq/client.rb:187 in atomic_push
vendor/bundle/ruby/2.0.0/gems/sidekiq-4.1.0/lib/sidekiq/client.rb:172 in block (2 levels) in raw_push
vendor/bundle/ruby/2.0.0/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:417 in block in namespaced_block
vendor/bundle/ruby/2.0.0/gems/redis-3.2.2/lib/redis.rb:2244 in block in multi
vendor/bundle/ruby/2.0.0/gems/redis-3.2.2/lib/redis.rb:57 in block in synchronize
vendor/ruby-2.0.0/lib/ruby/2.0.0/monitor.rb:211 in mon_synchronize
vendor/bundle/ruby/2.0.0/gems/redis-3.2.2/lib/redis.rb:57 in synchronize
vendor/bundle/ruby/2.0.0/gems/redis-3.2.2/lib/redis.rb:2237 in multi
vendor/bundle/ruby/2.0.0/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:414 in namespaced_block
vendor/bundle/ruby/2.0.0/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:259 in multi
vendor/bundle/ruby/2.0.0/gems/sidekiq-4.1.0/lib/sidekiq/client.rb:171 in block in raw_push
vendor/bundle/ruby/2.0.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:64 in block (2 levels) in with
vendor/bundle/ruby/2.0.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63 in handle_interrupt
vendor/bundle/ruby/2.0.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63 in block in with
vendor/bundle/ruby/2.0.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60 in handle_interrupt
vendor/bundle/ruby/2.0.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60 in with
vendor/bundle/ruby/2.0.0/gems/sidekiq-4.1.0/lib/sidekiq/client.rb:170 in raw_push
vendor/bundle/ruby/2.0.0/gems/sidekiq-4.1.0/lib/sidekiq/client.rb:67 in push
vendor/bundle/ruby/2.0.0/gems/sidekiq-4.1.0/lib/sidekiq/worker.rb:115 in client_push
vendor/bundle/ruby/2.0.0/gems/sidekiq-4.1.0/lib/sidekiq/worker.rb:59 in perform_async
app/workers/parent_worker.rb:13 in block in perform
```

If I rescue against that error, then the child worker job seems to not be enqueued but for some reason the parent worker's job count is still 1. Since the child worker job doesn't exist, the parent worker is forever stuck in limbo.

I would really appreciate any ideas you might have!

**Comment by anujdas** [comment] 2016-04-06 16:19
Hey @holoiii sorry for the late response! Can you give me an example of an invalid input string (converted to hex, if github doesn't like non-unicode)? I'd also appreciate if you could share how you're setting up your middlewares, since I noticed sidekiq-hierarchy isn't included in the stacktrace you provided. This shouldn't be happening: if a job fails to enqueue (via Sidekiq::Client#atomic_push), the middleware stack should see a nil job response, which should prevent sidekiq-hierarchy from recording anything (ref: https://github.com/anujdas/sidekiq-hierarchy/blob/master/lib/sidekiq/hierarchy/client/middleware.rb#L18). Or, in this case, the exception should just bubble up through the hierarchy middleware without triggering any job enqueue recording. Obviously though, it _is_ happening to you, so I'll see whether I can reproduce it.

**Comment by anujdas** [comment] 2016-04-06 18:32
@holoiii:

Never mind, I understand what's happening now. Sidekiq pre-processes jobs through all middlewares before it pushes them to redis (the serialization step here is what's failing for you). As a result, sidekiq-hierarchy runs successfully and, as far as it's aware, a job has been queued; by the time sidekiq raises, the middleware is no longer in the picture. I'll try to think of a way to fix this, but meanwhile it may be possible for you to implement a manual workaround by implementing the push code yourself and rescuing the appropriate error, then marking the job as completed: see https://github.com/mperham/sidekiq/blob/4489edd5a9278049ab79875401825214ba937b3e/lib/sidekiq/client.rb#L62-L70 and https://github.com/mperham/sidekiq/blob/4489edd5a9278049ab79875401825214ba937b3e/lib/sidekiq/worker.rb#L58-L60.

However, if I were you I'd just sanitize inputs before you go through the process of enqueueing; a simple wrapper around perform_async that did a JSON.encode on the args and aborted on exception would be much simpler, at the expense of some verbosity.

**Comment by anujdas** [comment] 2016-04-21 17:41
@holoiii does that help? Since I can't do anything about the issue from within sidekiq-hierarchy, I'm closing this out (let me know if you have any ideas, though!)

**Closed as completed by anujdas** 2016-04-21 17:41 UTC

**Comment by holoiii** [comment] 2016-05-05 21:14
@anujdas Thanks for the detailed response! I'll take some time to digest your suggestions and see if I can figure out a more permanent solution. My temporary solution was to do what you suggested, and sanitize the inputs before enqueueing, which has worked nicely so far.
